
[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
QSpin = "3f62d152-8970-4ff6-93e2-b431c80450c4"

[compat]
Plots = "1.41.5"
LaTeXStrings = "1.4.0"

[sources]
QSpin = {path = ".."}
